# Czas trwania anty logoutu w sekundach zależnie od tego, co zadało damage
Player: 15
Mob: 10
Other: 5

# Dozwolone komendy podczas antylogoutu
enabled-commands:
  - msg
  - r
  - op

# Wiadomości:
messages:
  # Gdy gracz próbuje użyć zakazanej komendy podczas walki
  command-in-combat: "&cNie możesz użyć tej komendy podczas walki!"
  # Wiadomość wysyłana wszystkim na chacie o tym, że gracz się wylogował podczas walki (%player% to gracz XD)
  logout: "&c&lKlockowaMasakra &6&l>>> &e&lGracz &c&l%player% &e&lwylogował się podczas walki!"
  # Wyświetlane od razu po rozpoczęciu antylogoutu (kolorki w formacie Legacy)
  # Domyślnie: "> NIE WYLOGOWYWUJ SIĘ! <"
  actionbar-1: "&x&f&f&0&0&0&0> NIE WYLOGOWYWUJ SIĘ! <"
  # Czas wyświetlania pierwszego napisu przed odpaleniem gradientu (w tickach)
  actionbar-1-delay: 20
  # Tekst, na którym ma być gradient (nie polecam zmieniać, bo się gradienty popsują, ale good luck)
  actionbar-2: "ANTY LOGOUT"
  # Wyświetlane po zakończeniu antylogoutu (to samo co na początku)
  actionbar-3: "&x&4&2&f&f&0&0Możesz się już wylogować"