name: NCode-AntyLogout
version: '${project.version}'
main: me.sajen.ncode.antylogout.Main
api-version: '1.17'
author: Sajen
commands:
  antylogout:
    description: Główna komenda pluginu NCode-Antylogout
    permission: ncode.antylogout.admin

permissions:
  ncode.antylogout.commands:
    description: Pozwala na używanie wszystkich komend podczas walki.
    default: op
  ncode.antylogout.logout:
    description: Pozwala na wylogowanie podczas walki bez zabicia.
    default: op
  ncode.antylogout.region:
    description: Pozwala wchodzić na regiony które są normalnie zablokowane podczas walki.
    default: op
  ncode.antylogout.admin:
    description: Pozwala na użycie komendy głównej pluginu.
    default: op